services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password12345
    ports:
      - 1433:1433
    volumes:
      - ./mssql_data:/var/opt/mssql/data
    networks:
      - lab01_asp.netcorewebapi
    
  lab01_asp.netcorewebapi:
    image: lab01_asp.netcorewebapi
    build:
      context: .
      dockerfile: Lab01_ASP.NETCoreWebAPI/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection="Server=sqlserver:1433;Database=Lab01_ASP;User=sa;Password=Password12345;TrustServerCertificate=True"
    ports:
      - 5000:80
    depends_on:
      - sqlserver
    networks:
      - lab01_asp.netcorewebapi
volumes:
  mssql_data:
networks:
  lab01_asp.netcorewebapi:
    driver: bridge